#!/bin/sh

mvn -o clean
mvn -o -Pprod clean package install

mvn -o -Pprod site site:deploy

cd search-core

mvn -o -Pprod site site:deploy

cd ../search-jfreereport

mvn -o -Pprod site site:deploy

cd ../search-example

mvn -o -Pprod site site:deploy

cd ../search-share

mvn -o -Pprod site site:deploy

cd ../search-share_nohibernate

mvn -o -Pprod site site:deploy


cd ..
